### ISSUE TITLE
Feature: Support running gowarcserver without badger

### ISSUE THREAD

**Issue by Avokadoen** [nlnwa/gowarcserver#22]
**Is your feature request related to a problem? Please describe.**
Collision of badger db folder can will cause panic. There is also overhead in running an empty DB 

**Describe the solution you'd like**
Allow user to use argument i.e ``--no-badger`` to disable badger db. This will make it easier to have parent gowarc servers (see issue #4) that only ask children with replicas 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by maeb** [comment]
No longer applies because proxy feature was removed.
