### ISSUE TITLE
Bug: docker artifact on master even if linting and tests fails

### ISSUE THREAD

**Issue by Avokadoen** [nlnwa/gowarcserver#35]
**Describe the bug**
When a new commit arrives in master, the CI will make an artifact even if the testing and linting CI fails

**To Reproduce**
Push to master

**Expected behavior**
Docker artifact is omitted in the event of failures in tests and linter

**Screenshots**
None

**Additional context**
Introduced in PR [34](https://github.com/nlnwa/gowarcserver/pull/34)

**Comment by Avokadoen** [comment]
Enabled protection on master (PR from other branch required). This will mitigate this issue a little bit.

**Comment by maeb** [comment]
Not an issue anymore. Test and lint runs on pull requests, release builds docker artifact  when tagging with "v*" on any branch.
