### ISSUE TITLE
Feature: Support revisit blocks without WARC-Refers-To header

### ISSUE THREAD

**Issue by Avokadoen** [nlnwa/gowarcserver#56]
**Is your feature request related to a problem? Please describe.**
It is valid to have records that only have WARC-Refers-To-Target-URI and WARC-Refers-To-Date (see [6.7.2](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#revisit)). This is currently not supported in gowarcserver 

**Describe the solution you'd like**
Add handling of records without WARC-Refers-To in the loader/loader.go Load function

**Comment by maeb** [comment]
Fixed in #77.
